In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X -X.mean()

In [3]:
layer = CenteredLayer()
X = torch.FloatTensor([1,2,3,4,5])
layer(X)

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128),
                    CenteredLayer())


In [8]:
Y=torch.rand((4, 8))
print(Y.mean())
Y = net(Y)
print(Y.mean())

tensor(0.5020)
tensor(8.9640e-09, grad_fn=<MeanBackward0>)


In [28]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn((in_units, units)))
        self.bias = nn.Parameter(torch.randn(units))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        # linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

注意.weight.data与.weight的区别

数值一样，但.weight forward出来全为零了

In [31]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6632,  0.6262, -0.1446],
        [ 1.1750,  2.3040, -0.2552],
        [ 1.0088, -0.3646, -0.7215],
        [ 0.1523, -0.3758, -0.8334],
        [ 0.5291,  1.8504,  0.2693]], requires_grad=True)

In [44]:
linear(torch.rand(2,5))

tensor([[0.8606, 0.1215, 0.0000],
        [1.8272, 2.1706, 0.0000]])

In [58]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[17.0957],
        [ 5.4124]])