In [1]:
import torch
from torch import nn



In [4]:
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros(size=(X.shape[0]-h+1, X.shape[1]-w+1)) # 卷积结果尺寸 5*5和3*3卷积，结果3*3
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=(X[i:i+h, j:j+w] * K).sum()
    return Y

In [5]:
X = torch.tensor([[0.,1.,2.],
                  [3.,4.,5.],
                  [6.,7.,8.]])
K = torch.tensor([[0.,1.],
                  [2.,3.]])
corr2d(X,K)

tensor([[19., 25.],
        [37., 43.]])

In [6]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight=nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(self, x):
        return corr2d(x, self.weight)+self.bias

In [14]:
X = torch.ones(size=(6,8))
X[:,2:6] = 0.
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [15]:
K = torch.tensor([[1., -1.]])
Y = corr2d(X=X, K=K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [24]:
# 学习卷积核
conv2d = nn.Conv2d(1,1,kernel_size=(1,2),bias=False)

# 这个二维卷积层使用四维输入和输出格式（批量大小、通道、高度、宽度），
# 其中批量大小和通道数都为1
X = X.reshape(1,1,6,8)
Y = Y.reshape(1,1,6,7) # 卷积结果 上面的矩阵，Y在这里是答案
lr=3e-2




In [25]:
conv2d.weight

Parameter containing:
tensor([[[[-0.4102, -0.1481]]]], requires_grad=True)

In [27]:
conv2d.weight.data

tensor([[[[-0.4102, -0.1481]]]])

In [26]:
conv2d.weight.data[:]

tensor([[[[-0.4102, -0.1481]]]])

In [28]:
for i in range(50):
    Y_hat = conv2d(X)
    l = (Y_hat-Y)**2
    conv2d.zero_grad()
    l.sum().backward()
    conv2d.weight.data -= lr*conv2d.weight.grad
    print(f'epoch{i+1}, loss {l.sum():.3f}')

epoch1, loss 20.026
epoch2, loss 9.280
epoch3, loss 4.490
epoch4, loss 2.281
epoch5, loss 1.216
epoch6, loss 0.679
epoch7, loss 0.394
epoch8, loss 0.235
epoch9, loss 0.144
epoch10, loss 0.089
epoch11, loss 0.056
epoch12, loss 0.035
epoch13, loss 0.022
epoch14, loss 0.014
epoch15, loss 0.009
epoch16, loss 0.006
epoch17, loss 0.004
epoch18, loss 0.002
epoch19, loss 0.002
epoch20, loss 0.001
epoch21, loss 0.001
epoch22, loss 0.000
epoch23, loss 0.000
epoch24, loss 0.000
epoch25, loss 0.000
epoch26, loss 0.000
epoch27, loss 0.000
epoch28, loss 0.000
epoch29, loss 0.000
epoch30, loss 0.000
epoch31, loss 0.000
epoch32, loss 0.000
epoch33, loss 0.000
epoch34, loss 0.000
epoch35, loss 0.000
epoch36, loss 0.000
epoch37, loss 0.000
epoch38, loss 0.000
epoch39, loss 0.000
epoch40, loss 0.000
epoch41, loss 0.000
epoch42, loss 0.000
epoch43, loss 0.000
epoch44, loss 0.000
epoch45, loss 0.000
epoch46, loss 0.000
epoch47, loss 0.000
epoch48, loss 0.000
epoch49, loss 0.000
epoch50, loss 0.000


In [29]:
conv2d.weight.data.reshape(1,2)

tensor([[ 1.0000, -1.0000]])